name: CD

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract updateSerial
      id: extract_serial
      run: |
        SERIAL=$(jq -r '.updateSerial' "vATIS-Profile-Hong-Kong-FIR-VHHK")
        echo "updateSerial=$SERIAL" >> $GITHUB_ENV

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${{ env.updateSerial }}" \
          "vATIS-Profile-Hong-Kong-FIR-VHHK" \
          --title "v${{ env.updateSerial }}" \
          --notes "Automated release for updateSerial v${{ env.updateSerial }}."
